services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobscout_dev"]
      interval: 5s
      timeout: 2s
      retries: 20

    # 🧠 Performance tuning with balanced durability
    command: >
      postgres -c listen_addresses='*'
               -c synchronous_commit=local
               -c wal_writer_delay=200ms
               -c max_wal_size=512MB
               -c shared_buffers=256MB

    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  app: {}
