services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app
    healthcheck:
      test: ["CMD", "mongodb", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 2s
      retries: 20
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    depends_on:
      - mongodb
    networks:
      - app
    logging:
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  mongo_data:

networks:
  app: {}
